version: '3'
services:
  api-solid-pg:
    image: bitnami/postgresql
    restart: always
    environment:
      POSTGRESQL_PASSWORD: docker
      POSTGRESQL_USERNAME: docker
      POSTGRESQL_DATABASE: apisolid
    ports:
      - 5432:5432
